Population / Per capita calcuations

Bigfoot Calcs.

In [ ]:
import pandas as pd

In [16]:
df = pd.read_csv('F:\\d10\\Projects\\bigfeet\\data\\bfro_reports_geocoded.csv')
df_pop = pd.read_csv('F:\\d10\\Projects\\bigfeet\\data\\census_state_pop.csv')

state_counts = df['state'].value_counts().reset_index()
state_counts.columns = ['state', 'count']


merged_df = pd.merge(state_counts, df_pop, left_on='state', right_on='NAME')

merged_df['entries_per_capita'] = merged_df['count'] / merged_df['POPESTIMATE2023']
state_counts = merged_df[['state', 'count', 'entries_per_capita']].sort_values(by='entries_per_capita', ascending=False)



df_final = pd.merge(df, state_counts[['state', 'entries_per_capita']], on='state', how='left')


output_path_final = 'F:\\d10\\Projects\\bigfeet\\data\\bigfeets_per_capita_sorted.csv'
df_final.to_csv(output_path_final, index=False)

In [18]:
df_final.head()

,observed,location_details,county,state,season,title,latitude,longitude,date,number,...,precip_type,pressure,summary,conditions,uv_index,visibility,wind_bearing,wind_speed,location,entries_per_capita
0,I am not sure how relevant this report will be...,"We were on our way to Rapid City, so we were h...",Washakie County,Wyoming,Summer,NaN,NaN,NaN,NaN,798.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000046
1,I don't know if what I saw was two bigfoots or...,"Heading to the deep mine Poca #2, the airshaft...",Wyoming County,West Virginia,Winter,Report 13237: Daylight sighting near an abando...,37.58135,-81.29745,2005-12-03,13237.0,...,"['rain', 'snow']",1018.7,Partly cloudy throughout the day with late aft...,"Snow, Rain, Partially cloudy",NaN,9.3,168.1,17.1,POINT(-81.29745 37.58135),0.000059
2,"My family and I went to Ludlow, Vermont for Co...",It's off Rt 100 outside of Ludlow Vermont. It ...,Windsor County,Vermont,Fall,Report 13285: Evening sighting by motorists on...,43.46540,-72.70510,2005-10-08,13285.0,...,['rain'],1011.8,Cloudy skies throughout the day with a chance ...,"Rain, Overcast",NaN,5.0,356.2,7.6,POINT(-72.7051 43.4654),0.000015
3,It was spring break 1984 and I was 16 at the t...,"Wythe county Virginia near Wytheville, looking...",Wythe County,Virginia,Spring,"Report 2285: Boy sees ""Bigfoot"" in the woods w...",37.22647,-81.09017,1984-04-08,2285.0,...,NaN,1020.9,Partly cloudy throughout the day.,Partially cloudy,NaN,13.0,107.3,11.5,POINT(-81.09017 37.22647),0.000009
4,It was the winter of 1996 and we were on our w...,"Hwy 182, Wood County Between Quitman, Texas an...",Wood County,Texas,Winter,Report 2048: Night time road crossing observation,32.79430,-95.54250,1996-12-22,2048.0,...,NaN,NaN,Partly cloudy throughout the day.,Partially cloudy,NaN,10.5,180.4,20.8,POINT(-95.5425 32.7943),0.000008

In [17]:
state_counts.head(50)

             state  count  entries_per_capita
0       Washington    610            0.000078
4           Oregon    249            0.000059
14   West Virginia    104            0.000059
17           Idaho     97            0.000049
36         Wyoming     27            0.000046
29         Montana     51            0.000045
15        Arkansas    103            0.000034
39          Alaska     21            0.000029
3             Ohio    306            0.000026
8         Missouri    159            0.000026
13        Kentucky    114            0.000025
16        Oklahoma     99            0.000024
7         Michigan    217            0.000022
10        Colorado    127            0.000022
32      New Mexico     42            0.000020
5         Illinois    238            0.000019
19         Alabama     95            0.000019
28            Iowa     56            0.000017
27            Utah     59            0.000017
44         Vermont     10            0.000015
30          Kansas     45            0.000015
21       Wisconsin     87            0.000015
43    South Dakota     13            0.000014
2          Florida    306            0.000014
18       Tennessee     96            0.000013
40           Maine     18            0.000013
25       Minnesota     73            0.000013
9          Georgia    129            0.000012
24         Indiana     79            0.000012
22         Arizona     85            0.000011
1       California    422            0.000011
42   New Hampshire     14            0.000010
23        Virginia     81            0.000009
11    Pennsylvania    120            0.000009
33       Louisiana     41            0.000009
20  North Carolina     90            0.000008
31  South Carolina     43            0.000008
41        Nebraska     15            0.000008
6            Texas    231            0.000008
37     Mississippi     22            0.000007
26      New Jersey     68            0.000007
12        New York    114            0.000006
38     Connecticut     21            0.000006
34        Maryland     35            0.000006
48    North Dakota      4            0.000005
46        Delaware      5            0.000005
47    Rhode Island      5            0.000005
35   Massachusetts     29            0.000004
45          Nevada      7            0.000002