UFO entries per capita

In [8]:
import pandas as pd

In [11]:
df = pd.read_csv('F:\\d10\\Projects\\bigfeet\\data\\nuforc_reports.csv')
df_pop = pd.read_csv('F:\\d10\\Projects\\bigfeet\\data\\census_state_pop.csv')

abrev_to_full = {
    'AL': 'Alabama', 'AK': 'Alaska', 'AZ': 'Arizona', 'AR': 'Arkansas', 'CA': 'California',
    'CO': 'Colorado', 'CT': 'Connecticut', 'DE': 'Delaware', 'FL': 'Florida', 'GA': 'Georgia',
    'HI': 'Hawaii', 'ID': 'Idaho', 'IL': 'Illinois', 'IN': 'Indiana', 'IA': 'Iowa',
    'KS': 'Kansas', 'KY': 'Kentucky', 'LA': 'Louisiana', 'ME': 'Maine', 'MD': 'Maryland',
    'MA': 'Massachusetts', 'MI': 'Michigan', 'MN': 'Minnesota', 'MS': 'Mississippi', 'MO': 'Missouri',
    'MT': 'Montana', 'NE': 'Nebraska', 'NV': 'Nevada', 'NH': 'New Hampshire', 'NJ': 'New Jersey',
    'NM': 'New Mexico', 'NY': 'New York', 'NC': 'North Carolina', 'ND': 'North Dakota', 'OH': 'Ohio',
    'OK': 'Oklahoma', 'OR': 'Oregon', 'PA': 'Pennsylvania', 'RI': 'Rhode Island', 'SC': 'South Carolina',
    'SD': 'South Dakota', 'TN': 'Tennessee', 'TX': 'Texas', 'UT': 'Utah', 'VT': 'Vermont',
    'VA': 'Virginia', 'WA': 'Washington', 'WV': 'West Virginia', 'WI': 'Wisconsin', 'WY': 'Wyoming'
}


df['state'] = df['state'].map(abrev_to_full).fillna(df['state'])

state_counts = df['state'].value_counts().reset_index()
state_counts.columns = ['state', 'count']


merged_df = pd.merge(state_counts, df_pop, left_on='state', right_on='NAME')

merged_df['entries_per_capita'] = merged_df['count'] / merged_df['POPESTIMATE2023']
state_counts = merged_df[['state', 'count', 'entries_per_capita']].sort_values(by='entries_per_capita', ascending=False)



df_final = pd.merge(df, state_counts[['state', 'entries_per_capita']], on='state', how='left')


output_path_final = 'F:\\d10\\Projects\\bigfeet\\data\\export\\ufo_per_capita_sorted_converted.csv'
df_final.to_csv(output_path_final, index=False)

In [13]:
state_counts.head(50)

             state  count  entries_per_capita
45         Vermont    584            0.000902
2       Washington   6896            0.000883
38         Montana    964            0.000851
43          Alaska    619            0.000844
34           Maine   1145            0.000820
35   New Hampshire   1139            0.000812
11          Oregon   3400            0.000803
27      New Mexico   1585            0.000750
46         Wyoming    396            0.000678
31           Idaho   1309            0.000666
6          Arizona   4727            0.000636
44    Rhode Island    585            0.000534
23     Connecticut   1930            0.000534
12        Colorado   3085            0.000525
25          Nevada   1622            0.000508
39   West Virginia    867            0.000490
42          Hawaii    646            0.000450
14        Missouri   2692            0.000434
28            Utah   1445            0.000423
48    South Dakota    373            0.000406
21  South Carolina   2153            0.000401
19       Wisconsin   2357            0.000399
32        Arkansas   1220            0.000398
0       California  15454            0.000397
36          Kansas   1128            0.000384
47        Delaware    395            0.000383
15         Indiana   2609            0.000380
5     Pennsylvania   4779            0.000369
33            Iowa   1172            0.000365
18   Massachusetts   2557            0.000365
7             Ohio   4271            0.000362
26        Kentucky   1617            0.000357
22       Minnesota   2014            0.000351
29        Oklahoma   1414            0.000349
9         Michigan   3489            0.000348
1          Florida   7823            0.000346
49    North Dakota    266            0.000339
41        Nebraska    667            0.000337
8         Illinois   4112            0.000328
10  North Carolina   3483            0.000321
20       Tennessee   2195            0.000308
13      New Jersey   2759            0.000297
17        Virginia   2565            0.000294
4         New York   5624            0.000287
24        Maryland   1733            0.000280
30         Alabama   1322            0.000259
40     Mississippi    746            0.000254
37       Louisiana   1075            0.000235
16         Georgia   2589            0.000235
3            Texas   5816            0.000191